# Generated by Django 3.1.6 on 2021-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210217_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('maroon', 'Maroon'), ('red', 'Red'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('green', 'Green'), ('lime', 'Lime'), ('olive', 'Olive'), ('yellow', 'Yellow'), ('navy', 'Navy'), ('blue', 'Blue'), ('teal', 'Teal'), ('aqua', 'Aqua')], default='green', max_length=10),
        ),
    ]
