# Generated by Django 3.1.6 on 2021-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('maroon', 'Maroon'), ('red', 'Red'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('green', 'Green'), ('lime', 'Lime'), ('olive', 'Olive'), ('yellow', 'Yellow'), ('navy', 'Navy'), ('blue', 'Blue'), ('teal', 'Teal'), ('aqua', 'Aqua'), ('orange', 'Orange')], default='green', max_length=10),
        ),
    ]
