# Generated by Django 3.1.6 on 2021-02-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210218_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('purple', 'Purple'), ('green', 'Green'), ('orange', 'Orange')], default='green', max_length=10),
        ),
    ]
