# Generated by Django 3.1.6 on 2021-03-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210226_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Dimension',
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='dimension',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='recipesingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dimension',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.dimension'),
            preserve_default=False,
        ),
    ]
