# Generated by Django 3.1.6 on 2021-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210301_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='title',
        ),
        migrations.AlterField(
            model_name='dimension',
            name='abbr',
            field=models.CharField(default='', max_length=25),
        ),
    ]
