# Generated by Django 3.1.6 on 2021-03-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210302_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='text',
            new_name='description',
        ),
    ]
