# Generated by Django 3.1.6 on 2021-04-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20210414_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('PU', 'purple'), ('GR', 'green'), ('OR', 'orange')], default='GR', max_length=10, verbose_name='Цвет'),
        ),
    ]
