# Generated by Django 3.1.6 on 2021-02-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodassist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='contraction',
            field=models.CharField(default='.', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
