name: foodgram_workflow

on: [push]

jobs:
  tests:
    name: Test FooDGRAM app with pytest and flake8
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.YAMDB_DJANGO_SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install flake8
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 --exclude=migrations,tests,settings.py foodgram/

    - name: Test with Django test runner
      run: python3 foodgram/manage.py test -v 2
      
deploy:
    name: Deploy YaMDB to production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          rm: true
          source: "docker-compose.yaml,nginx,postgres"
          target: "/home/${{ secrets.REMOTE_USERNAME }}/foodgram_app/tmp"
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST_IP }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            cd foodgram_app/
            cp -fr tmp/* .
            touch TEST.OK